import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import React from "react";
import SidebarToggle from "@/components/sidebar/SidebarToggle";
import Breadcrumbs from "@/components/breadcrumbs/Breadcrumbs";
import Footer from "@/components/footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ticket-App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-etuwaCustom-wb`}
      >
        <div className="flex flex-col min-h-screen bg-etuwaCustom-wb">
          {/* Header */}
          <SidebarToggle>
            <div className="">
              <Breadcrumbs />
              {children}
            </div>
          </SidebarToggle>
        </div>
        <Footer />
      </body>
    </html>
  );
}
